---
version: "3"

tasks:
  default:
    desc: "Run godoc on all packages"
    dir: ../..
    vars:
      package:
        sh: go mod edit -json | jq .Module.Path -r
      packages:
        sh: go list ./... | sed -e 's|{{.package}}|.|g'
    silent: true
    cmds:
      - |
        set -e;
        {{- range $i, $package := .packages | splitLines -}}
          echo -e "# Package: {{ $package }}\n"
          go doc -all {{ $package }} || true
        {{ end -}}
