---
version: "3"

tasks:
  default:
    desc: "Run godoc on all packages"
    dir: ../..
    vars:
      package:
        sh: go list .
      packages:
        sh: go list ./... | sed -e 's|{{.package}}|.|g'
    silent: true
    cmds:
      - |
        set -e;
        {{- range $i, $package := .packages | splitLines -}}
          go doc {{ $package }}
        {{ end -}}
