---
version: "3"

includes:
  services:
    taskfile: ../../docker/services/Taskfile.yml
    dir: ../../docker/services

vars:
  run: .

tasks:
  default:
    desc: "Run tests"
    deps: [ services:up ]
    requires:
      vars: [run]
    cmds:
      - defer: { task: services:down }
      - goimports -w .
      - go fmt ./...
      - go test -count=1 -run='({{.run}})' -cover -coverprofile=pkg.cov -v .

  cover:
    desc: "Show source coverage"
    aliases: [coverage, cov]
    cmds:
      - go tool cover -func=pkg.cov

  uncover:
    desc: "Show uncovered source"
    cmds:
      - uncover pkg.cov

  install:uncover:
    desc: "Install uncover"
    env:
      GOBIN: /usr/local/bin
    cmds:
      - go install github.com/gregoryv/uncover/...@latest
