---
version: "3"

vars:
  run: .

tasks:
  default:
    desc: "Run tests"
    requires:
      vars: [run]
    cmds:
      - goimports -w .
      - go fmt ./...
      - task: test
        vars:
          run: '{{.run}}'

  test:
    desc: "Run tests"
    requires:
      vars: [run]
    cmds:
      - go test -count=1 -run='({{.run}})' -cover -coverprofile=pkg.cov -v .

  stress:
    desc: "Run stress tests"
    requires:
      vars: [run]
    cmds:
      - go test -count=2000 -run='({{.run}})' -cover -coverprofile=pkg.cov .

  cover:
    desc: "Show source coverage"
    aliases: [coverage, cov]
    cmds:
      - go tool cover -func=pkg.cov

  uncover:
    desc: "Show uncovered source"
    cmds:
      - uncover pkg.cov

  install:uncover:
    desc: "Install uncover"
    env:
      GOBIN: /usr/local/bin
    cmds:
      - go install github.com/gregoryv/uncover/...@latest
