---
name: "Cleanup Python"
description: "A composite action to remove preinstalled Python versions in a GitHub runner."

runs:
  using: "composite"
  steps:
    - name: Uninstall preinstalled Python version
      shell: bash
      run: sudo apt-get remove python3 --purge -y
