# Options for analysis running.
run:
  timeout: 20m
  tests: true

  # Be as complete as possible when reporting issues
  max-issues-per-linter: 0
  max-same-issues: 0

  # If set we pass it to "go list -mod={option}". From "go help modules":
  # If invoked with -mod=readonly, the go command is disallowed from the implicit
  # automatic updating of go.mod described above. Instead, it fails when any changes
  # to go.mod are needed. This setting is most useful to check that go.mod does
  # not need updates, such as in a continuous integration and testing system.
  # If invoked with -mod=vendor, the go command assumes that the vendor
  # directory holds the correct copies of dependencies and ignores
  # the dependency descriptions in go.mod.
  #
  # Allowed values: readonly|vendor|mod
  # By default, it isn't set.
  modules-download-mode: readonly

  # Allow multiple parallel golangci-lint instances running.
  # If false (default) - golangci-lint acquires file lock on start.
  allow-parallel-runners: false

linters:
  disable:
    - varnamelen
    - tagliatelle
    - testpackage
    - paralleltest
    - ireturn
    - goimports
  enable:
    - govet
    - gofumpt
    - forbidigo
    - gochecknoinits
    - thelper
    - errcheck
    - errorlint
    - noctx
    - dupl
    - nilerr
    - misspell
    - revive
    - whitespace
    - wsl

linters-settings:
  misspell:
    ignore-words:
      - tempset  # temporary set, not "tempest"

  whitespace:
    multi-if: true  # Enforces newlines (or comments) after every multi-line if statement
    multi-func: true  # Enforces newlines (or comments) after every multi-line function signature

  wsl:
    # Controls if you may cuddle assignments and anything without needing an empty line between them.
    allow-assign-and-anything: false
    # Allow calls and assignments to be cuddled as long as the lines have any matching variables, fields or types.
    # Default is true.
    allow-assign-and-call: true
    # Controls if you may end case statements with a whitespace.
    allow-case-trailing-whitespace: true
    # Allow declarations (var) to be cuddled.
    allow-cuddle-declarations: true
    # Allow multiline assignments to be cuddled. Default is true.
    allow-multiline-assign: true
    # This option allows whitespace after each comment group that begins a block.
    allow-separated-leading-comment: false
    # Allow trailing comments in ending of blocks
    allow-trailing-comment: false
    # Enforces that an if statement checking an error variable
    # is cuddled with the line that assigned that error variable.
    enforce-err-cuddling: true
    # Force newlines in end of case at this limit (0 = never).
    force-case-trailing-whitespace: 0
    # Enforces that an assignment which is actually a short declaration (using :=)
    # is only allowed to cuddle with other short declarations, and not plain assignments, blocks, etc.
    force-short-decl-cuddling: false
    # Append is only allowed to be cuddled if appending value is matching variables, fields or types on line above.
    # Default is true.
    strict-append: true

  fobidigo:
    forbid:
      - p: ^fmt\.Print.*$
        msg: Do not commit print statements, use t.Log or Logrus.
      - p: ^net\/http\.(Get|Head|Post|Form).*$
        msg: Do not use top level http package functions, NewRequestWithContext is encouraged.
    exclude-godoc-examples: false
    analyze-types: true

  revive:
    ignore-generated-header: true
    severity: error
    enable-all-rules: false
    rules:
      - name: unused-parameter
        disabled: false
        arguments:
          - allowRegex: "^_"
      - name: import-shadowing
        disabled: false
      - name: exported
        disabled: false

  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - (*github.com/TykTechnologies/tyk/gateway.Test).Run
      - time.Parse

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-generated: strict
  exclude-files:
    - ".*\\.pb\\.go$"
    - ".*/mock/.+\\.go$"
    - ".*/bindata.go$"
  exclude-dirs:
    - ci
    - bin
    - webclient
    - portal
  exclude-rules:
    - path: ^cli/
      linters:
        - forbidigo # cli package uses fmt.Print by design
    - path: _test\.go
      linters:
        - dupl # many functions looks like dupes
        - gocyclo # many functions can be very long
        - funlen # many functions can be very long
        - gosec # tests don't have CVEs
  exclude:
    - G404    # Use of weak random number generator (math/rand instead of crypto/rand)
    - SA9004  # only the first constant in this group has an explicit type
    - SA1019  # Warning on deprecated imports (stdlib ioutil, grpc import)
