services:
  tyk:
    image: internal/tyk-gateway
    networks: [ proxy ]
    build: .
    ports:
    - 9000:8080
    volumes:
    - ./tyk.conf.example:/opt/tyk-gateway/tyk.conf

  redis:
    image: redis:4.0-alpine
    networks: [ proxy ]
    ports:
    - 6379:6379
    command: redis-server --appendonly yes

networks:
  proxy:
    name: proxy
    driver: bridge