services:
  tyk_1:
    container_name: "tyk"
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis

  redis:
    image: redis:4.0-alpine
    networks: [ proxy ]
    ports:
    - 6379:6379
    command: redis-server --appendonly yes

networks:
  proxy:
    name: proxy
    driver: bridge