---
version: "3"

tasks:
  gen:goreleaser:
    desc: "Update goreleaser config extra_files"
    vars:
      pluginTemp: /tmp/plugin-compiler.extra_paths
    cmds:
      - go list ./... | perl -p -e 's/.+tyk\///g' | grep -v github | perl -p -e 's/\/.+//g' | sort | uniq > {{.pluginTemp}}
      - echo -e "go.mod\ngo.sum\nmain.go\nci/images/plugin-compiler" >> {{.pluginTemp}}
      - |
        set -x
        replacement=$(cat {{.pluginTemp}} | paste -sd , - | sed -e 's/,/","/g')
        yq -i ".dockers[0].extra_files |= [\"$replacement\"]" ci/goreleaser/goreleaser-el7.yml
        yq -i ".dockers[4].extra_files |= [\"$replacement\"]" ci/goreleaser/goreleaser.yml
      - rm -f {{.pluginTemp}}

  test:goreleaser:
    desc: "Test goreleaser locally"
    deps:
      - gen:goreleaser
    cmds:
      - echo goreleaser release --clean --snapshot -f ci/goreleaser/goreleaser.yml
