---
version: "3"

includes:
  lint: .taskfiles/lint.yml
  deps: .taskfiles/deps/Taskfile.yml
  opentelemetry:
    taskfile: ci/tests/tracing/Taskfile.yml
    dir: ci/tests/tracing/

tasks:
  docker:
    desc: "build Tyk gateway internal/tyk-gateway"
    cmds:
      - docker build --platform "linux/amd64" --rm -t internal/tyk-gateway .
    sources:
      - go.mod
      - go.sum
      - "./**/*.go"

  test:plugin-compiler:
    desc: "Plugin compiler local build/test"
    cmds:
      - docker build --build-arg GO_VERSION=1.22 --build-arg BASE_IMAGE=tykio/golang-cross:1.22-bookworm --build-arg GITHUB_TAG=v5.1.0-alpha18 --build-arg GITHUB_SHA=$(git rev-parse HEAD) --platform=linux/amd64 --rm -t internal/plugin-compiler -f ci/images/plugin-compiler/Dockerfile .
      - docker run -it -e GOARCH=arm64 -e GOOS=linux --rm -v $(readlink -f .)/ci/images/plugin-compiler/data/basic-plugin:/plugin-source internal/plugin-compiler basic-plugin.so
      - docker run -it --rm -v $PWD:/go/src/github.com/TykTechnologies/tyk -w /go/src/github.com/TykTechnologies/tyk tykio/golang-cross:1.22-bookworm go build -trimpath -tags=goplugin .
      - ./tyk plugin load -f ./ci/images/plugin-compiler/data/basic-plugin/basic-plugin*.so -s MyPluginPre
      - docker rmi internal/plugin-compiler

  test:goreleaser:
    desc: "Test goreleaser locally"
    vars:
      pluginTemp: /tmp/plugin-compiler.extra_paths
    cmds:
      - go list ./... | perl -p -e 's/.+tyk\///g' | grep -v github | perl -p -e 's/\/.+//g' | sort | uniq > {{.pluginTemp}}
      - echo -e "go.mod\ngo.sum\nmain.go\nci/images/plugin-compiler" >> {{.pluginTemp}}
      - |
        set -x
        replacement=$(cat {{.pluginTemp}} | paste -sd , - | sed -e 's/,/","/g')
        yq -i ".dockers[4].extra_files |= [\"$replacement\"]" ci/goreleaser/goreleaser-5.0.yml
        yq -i ".dockers[0].extra_files |= [\"$replacement\"]" ci/goreleaser/goreleaser-el7.yml
        yq -i ".dockers[4].extra_files |= [\"$replacement\"]" ci/goreleaser/goreleaser.yml
      - echo goreleaser release --clean --snapshot -f ci/goreleaser/goreleaser.yml

  test:build:
    desc: "Build with go 1.22"
    vars:
      buildDir: /src
    cmds:
      - |
        docker run --rm \
                   -v $PWD:{{.buildDir}} \
                   -v /var/run/docker.sock:/var/run/docker.sock \
                   -w {{.buildDir}} \
                   -v /cache:/cache \
                   -e GOMODCACHE=/cache/mod \
                   -e GOCACHE=/cache/go-build \
                  tykio/golang-cross:1.22-bookworm \
                  bash -c "git config --global --add safe.directory {{.buildDir}}; goreleaser --clean -f ci/goreleaser/goreleaser.yml --snapshot --skip=sign"

  test:build-binary:
    desc: "Build with go 1.22"
    vars:
      buildDir: /src
    cmds:
      - |
        docker run --rm \
                   -v $PWD:{{.buildDir}} \
                   -v /var/run/docker.sock:/var/run/docker.sock \
                   -w {{.buildDir}} \
                   -v /cache:/cache \
                   -e GOMODCACHE=/cache/mod \
                   -e GOCACHE=/cache/go-build \
                  tykio/golang-cross:1.22-bookworm \
                  bash -c "git config --global --add safe.directory {{.buildDir}}; goreleaser build --single-target --debug --clean -f ci/goreleaser/goreleaser.yml --snapshot"
