// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: coprocess_return_overrides.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "coprocess_return_overrides.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace coprocess {

namespace {

const ::google::protobuf::Descriptor* ReturnOverrides_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ReturnOverrides_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_coprocess_5freturn_5foverrides_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_coprocess_5freturn_5foverrides_2eproto() {
  protobuf_AddDesc_coprocess_5freturn_5foverrides_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "coprocess_return_overrides.proto");
  GOOGLE_CHECK(file != NULL);
  ReturnOverrides_descriptor_ = file->message_type(0);
  static const int ReturnOverrides_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReturnOverrides, response_code_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReturnOverrides, response_error_),
  };
  ReturnOverrides_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ReturnOverrides_descriptor_,
      ReturnOverrides::internal_default_instance(),
      ReturnOverrides_offsets_,
      -1,
      -1,
      -1,
      sizeof(ReturnOverrides),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ReturnOverrides, _internal_metadata_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_coprocess_5freturn_5foverrides_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ReturnOverrides_descriptor_, ReturnOverrides::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_coprocess_5freturn_5foverrides_2eproto() {
  ReturnOverrides_default_instance_.Shutdown();
  delete ReturnOverrides_reflection_;
}

void protobuf_InitDefaults_coprocess_5freturn_5foverrides_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::GetEmptyString();
  ReturnOverrides_default_instance_.DefaultConstruct();
  ReturnOverrides_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_coprocess_5freturn_5foverrides_2eproto_once_);
void protobuf_InitDefaults_coprocess_5freturn_5foverrides_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_coprocess_5freturn_5foverrides_2eproto_once_,
                 &protobuf_InitDefaults_coprocess_5freturn_5foverrides_2eproto_impl);
}
void protobuf_AddDesc_coprocess_5freturn_5foverrides_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_coprocess_5freturn_5foverrides_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n coprocess_return_overrides.proto\022\tcopr"
    "ocess\"@\n\017ReturnOverrides\022\025\n\rresponse_cod"
    "e\030\001 \001(\005\022\026\n\016response_error\030\002 \001(\tb\006proto3", 119);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "coprocess_return_overrides.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_coprocess_5freturn_5foverrides_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_coprocess_5freturn_5foverrides_2eproto_once_);
void protobuf_AddDesc_coprocess_5freturn_5foverrides_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_coprocess_5freturn_5foverrides_2eproto_once_,
                 &protobuf_AddDesc_coprocess_5freturn_5foverrides_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_coprocess_5freturn_5foverrides_2eproto {
  StaticDescriptorInitializer_coprocess_5freturn_5foverrides_2eproto() {
    protobuf_AddDesc_coprocess_5freturn_5foverrides_2eproto();
  }
} static_descriptor_initializer_coprocess_5freturn_5foverrides_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ReturnOverrides::kResponseCodeFieldNumber;
const int ReturnOverrides::kResponseErrorFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ReturnOverrides::ReturnOverrides()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_coprocess_5freturn_5foverrides_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:coprocess.ReturnOverrides)
}

void ReturnOverrides::InitAsDefaultInstance() {
}

ReturnOverrides::ReturnOverrides(const ReturnOverrides& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:coprocess.ReturnOverrides)
}

void ReturnOverrides::SharedCtor() {
  response_error_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  response_code_ = 0;
  _cached_size_ = 0;
}

ReturnOverrides::~ReturnOverrides() {
  // @@protoc_insertion_point(destructor:coprocess.ReturnOverrides)
  SharedDtor();
}

void ReturnOverrides::SharedDtor() {
  response_error_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ReturnOverrides::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ReturnOverrides::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ReturnOverrides_descriptor_;
}

const ReturnOverrides& ReturnOverrides::default_instance() {
  protobuf_InitDefaults_coprocess_5freturn_5foverrides_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<ReturnOverrides> ReturnOverrides_default_instance_;

ReturnOverrides* ReturnOverrides::New(::google::protobuf::Arena* arena) const {
  ReturnOverrides* n = new ReturnOverrides;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void ReturnOverrides::Clear() {
// @@protoc_insertion_point(message_clear_start:coprocess.ReturnOverrides)
  response_code_ = 0;
  response_error_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool ReturnOverrides::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:coprocess.ReturnOverrides)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional int32 response_code = 1;
      case 1: {
        if (tag == 8) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &response_code_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_response_error;
        break;
      }

      // optional string response_error = 2;
      case 2: {
        if (tag == 18) {
         parse_response_error:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_response_error()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->response_error().data(), this->response_error().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "coprocess.ReturnOverrides.response_error"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:coprocess.ReturnOverrides)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:coprocess.ReturnOverrides)
  return false;
#undef DO_
}

void ReturnOverrides::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:coprocess.ReturnOverrides)
  // optional int32 response_code = 1;
  if (this->response_code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->response_code(), output);
  }

  // optional string response_error = 2;
  if (this->response_error().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->response_error().data(), this->response_error().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "coprocess.ReturnOverrides.response_error");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->response_error(), output);
  }

  // @@protoc_insertion_point(serialize_end:coprocess.ReturnOverrides)
}

::google::protobuf::uint8* ReturnOverrides::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:coprocess.ReturnOverrides)
  // optional int32 response_code = 1;
  if (this->response_code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->response_code(), target);
  }

  // optional string response_error = 2;
  if (this->response_error().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->response_error().data(), this->response_error().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "coprocess.ReturnOverrides.response_error");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->response_error(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:coprocess.ReturnOverrides)
  return target;
}

size_t ReturnOverrides::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:coprocess.ReturnOverrides)
  size_t total_size = 0;

  // optional int32 response_code = 1;
  if (this->response_code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->response_code());
  }

  // optional string response_error = 2;
  if (this->response_error().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->response_error());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ReturnOverrides::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:coprocess.ReturnOverrides)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const ReturnOverrides* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ReturnOverrides>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:coprocess.ReturnOverrides)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:coprocess.ReturnOverrides)
    UnsafeMergeFrom(*source);
  }
}

void ReturnOverrides::MergeFrom(const ReturnOverrides& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:coprocess.ReturnOverrides)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void ReturnOverrides::UnsafeMergeFrom(const ReturnOverrides& from) {
  GOOGLE_DCHECK(&from != this);
  if (from.response_code() != 0) {
    set_response_code(from.response_code());
  }
  if (from.response_error().size() > 0) {

    response_error_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.response_error_);
  }
}

void ReturnOverrides::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:coprocess.ReturnOverrides)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ReturnOverrides::CopyFrom(const ReturnOverrides& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:coprocess.ReturnOverrides)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool ReturnOverrides::IsInitialized() const {

  return true;
}

void ReturnOverrides::Swap(ReturnOverrides* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ReturnOverrides::InternalSwap(ReturnOverrides* other) {
  std::swap(response_code_, other->response_code_);
  response_error_.Swap(&other->response_error_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ReturnOverrides::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ReturnOverrides_descriptor_;
  metadata.reflection = ReturnOverrides_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ReturnOverrides

// optional int32 response_code = 1;
void ReturnOverrides::clear_response_code() {
  response_code_ = 0;
}
::google::protobuf::int32 ReturnOverrides::response_code() const {
  // @@protoc_insertion_point(field_get:coprocess.ReturnOverrides.response_code)
  return response_code_;
}
void ReturnOverrides::set_response_code(::google::protobuf::int32 value) {
  
  response_code_ = value;
  // @@protoc_insertion_point(field_set:coprocess.ReturnOverrides.response_code)
}

// optional string response_error = 2;
void ReturnOverrides::clear_response_error() {
  response_error_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& ReturnOverrides::response_error() const {
  // @@protoc_insertion_point(field_get:coprocess.ReturnOverrides.response_error)
  return response_error_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ReturnOverrides::set_response_error(const ::std::string& value) {
  
  response_error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:coprocess.ReturnOverrides.response_error)
}
void ReturnOverrides::set_response_error(const char* value) {
  
  response_error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:coprocess.ReturnOverrides.response_error)
}
void ReturnOverrides::set_response_error(const char* value, size_t size) {
  
  response_error_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:coprocess.ReturnOverrides.response_error)
}
::std::string* ReturnOverrides::mutable_response_error() {
  
  // @@protoc_insertion_point(field_mutable:coprocess.ReturnOverrides.response_error)
  return response_error_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* ReturnOverrides::release_response_error() {
  // @@protoc_insertion_point(field_release:coprocess.ReturnOverrides.response_error)
  
  return response_error_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void ReturnOverrides::set_allocated_response_error(::std::string* response_error) {
  if (response_error != NULL) {
    
  } else {
    
  }
  response_error_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), response_error);
  // @@protoc_insertion_point(field_set_allocated:coprocess.ReturnOverrides.response_error)
}

inline const ReturnOverrides* ReturnOverrides::internal_default_instance() {
  return &ReturnOverrides_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace coprocess

// @@protoc_insertion_point(global_scope)
