---
version: "3"

includes:
  services:
    taskfile: ../docker/services/Taskfile.yml
    dir: ../docker/services

tasks:
  default:
    desc: "Run everything"
    cmds:
      - task: test
      - task: lint

  test:
    desc: "Run tests"
    deps: [ services:up ]
    cmds:
      - defer: { task: services:down }
      - go fmt ./...
      - go test -count=1 ./...

  # lint target is run from CI
  lint:
    desc: "Ensure linter pass"
    cmds:
      # the replacement exists as a hack for:
      # https://github.com/grpc/grpc-go/issues/7350
      - sed -i -e 's/compatibility$/compatibility./g' *.pb.go
      - schema-gen extract -o - | schema-gen lint -i -

  deps:
    desc: "Update deps"
    cmds:
      - go install github.com/TykTechnologies/exp/cmd/schema-gen@main
