---
version: "3"

vars:
  testArgs: -v

tasks:
  test:
    desc: "Run tests (requires redis)"
    cmds:
      - task: fmt
      - go test {{.testArgs}} -count=1 -gcflags="-m=3" -cover -coverprofile=rate.cov .

  bench:
    desc: "Run benchmarks"
    cmds:
      - task: fmt
      - go test {{.testArgs}} -count=1 -tags integration -bench=. -benchtime=10s -benchmem .

  fmt:
    internal: true
    desc: "Invoke fmt"
    cmds:
      - goimports -w .
      - go fmt ./...

  cover:
    desc: "Show source coverage"
    aliases: [coverage, cov]
    cmds:
      - go tool cover -func=rate.cov

  uncover:
    desc: "Show uncovered source"
    cmds:
      - uncover rate.cov

  install:uncover:
    desc: "Install uncover"
    internal: true
    env:
      GOBIN: /usr/local/bin
    cmds:
      - go install github.com/gregoryv/uncover/...@latest
