---
version: '3'

tasks:
  default:
    desc: 'Install CI tooling'
    deps:
      - goimports
      - golangci-lint
      - faillint
      - mockgen
      - setup_hooks
    cmds:
      - for: ['go-fsck', 'schema-gen', 'summary']
        task: exp
        vars:
          name: '{{.ITEM}}'

  mockgen:
    internal: true
    desc: 'Install go.uber.org/mock mockgen'
    status:
      - type mockgen
    cmds:
      - go install go.uber.org/mock/mockgen@v0.4.0

  goimports:
    internal: true
    desc: 'Install x/tools goimports'
    status:
      - type goimports
    cmds:
      - go install golang.org/x/tools/cmd/goimports@latest

  golangci-lint:
    internal: true
    desc: 'Install golangci-lint'
    status:
      - type golangci-lint
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.55.2

  faillint:
    internal: true
    desc: 'Install fatih/faillint'
    status:
      - type faillint
    cmds:
      - go install github.com/fatih/faillint@latest

  exp:
    desc: 'Install exp/cmd'
    requires:
      vars: [name]
    status:
      - type {{.name}}
    cmds:
      - go install github.com/TykTechnologies/exp/cmd/{{.name}}@main

  setup_hooks:
    desc: Sets up the pre commit hooks
    cmds:
      - mkdir -p .git/hooks
      - cp scripts/pre-commit.sh .git/hooks/pre-commit
      - chmod +x .git/hooks/pre-commit
      - echo "Pre-commit hook has been set up."