---
version: '3'

tasks:
  default:
    desc: 'Install CI tooling'
    deps:
      - goimports
      - golangci-lint
      - faillint
      - mockgen
      - schema-gen

  mockgen:
    internal: true
    desc: 'Install golang/mock mockgen'
    status:
      - type mockgen
    cmds:
      - go install github.com/golang/mock/mockgen@v1.6.0

  goimports:
    internal: true
    desc: 'Install x/tools goimports'
    status:
      - type goimports
    cmds:
      - go install golang.org/x/tools/cmd/goimports@latest

  golangci-lint:
    internal: true
    desc: 'Install golangci-lint'
    status:
      - type golangci-lint
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.45.0

  faillint:
    internal: true
    desc: 'Install fatih/faillint'
    status:
      - type faillint
    cmds:
      - go install github.com/fatih/faillint@latest

  schema-gen:
    internal: true
    desc: 'Install exp/schema-gen'
    status:
      - type schema-gen
    cmds:
      - go install github.com/TykTechnologies/exp/cmd/schema-gen@main
