#!/bin/sh



# Generated by: tyk-ci/wf-gen
# Generated on: Wednesday 23 February 2022 07:20:32 PM UTC

# Generation commands:
# ./pr.zsh -title Sync from latest releng templates -branch td-883-test -base td-883-test -repos tyk -p
# m4 -E -DxREPO=tyk


if command -V systemctl >/dev/null 2>&1; then
    if [ ! -f /lib/systemd/system/tyk-gateway.service ]; then
        cp /opt/tyk-gateway/install/inits/systemd/system/tyk-gateway.service /lib/systemd/system/tyk-gateway.service
    fi
else
    if [ ! -f /etc/init.d/tyk-gateway ]; then
        cp /opt/tyk-gateway/install/inits/sysv/init.d/tyk-gateway /etc/init.d/tyk-gateway
    fi
fi
