#!/bin/bash
# This script compiles gateway.pyx using Cython
# and patches the binding file to include custom build tags (coprocess, python)

cd tyk/
rm gateway.c
echo "Cython compilation..."
cythonize gateway.pyx
echo "Appending build tags!"
echo -e "// +build coprocess\n// +build python\n\n$(cat gateway.c)" > gateway.c
echo "Done"
