# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: coprocess_response_object.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63oprocess_response_object.proto\x12\tcoprocess\"\xdd\x01\n\x0eResponseObject\x12\x13\n\x0bstatus_code\x18\x01 \x01(\x05\x12\x10\n\x08raw_body\x18\x02 \x01(\x0c\x12\x0c\n\x04\x62ody\x18\x03 \x01(\t\x12\x37\n\x07headers\x18\x04 \x03(\x0b\x32&.coprocess.ResponseObject.HeadersEntry\x12-\n\x12multivalue_headers\x18\x05 \x03(\x0b\x32\x11.coprocess.Header\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"%\n\x06Header\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x03(\tB\x0cZ\n/coprocessb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'coprocess_response_object_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\n/coprocess'
  _globals['_RESPONSEOBJECT_HEADERSENTRY']._loaded_options = None
  _globals['_RESPONSEOBJECT_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_RESPONSEOBJECT']._serialized_start=47
  _globals['_RESPONSEOBJECT']._serialized_end=268
  _globals['_RESPONSEOBJECT_HEADERSENTRY']._serialized_start=222
  _globals['_RESPONSEOBJECT_HEADERSENTRY']._serialized_end=268
  _globals['_HEADER']._serialized_start=270
  _globals['_HEADER']._serialized_end=307
# @@protoc_insertion_point(module_scope)
