---
version: "3"

vars:
  testArgs: -v
  coverpkg: ./...,github.com/TykTechnologies/tyk/internal/httputil/...

tasks:
  test:
    desc: "Run tests (requires redis)"
    cmds:
      - task: fmt
      - go test {{.testArgs}} -count=1 -cover -coverprofile=rate.cov -coverpkg={{.coverpkg}} ./...

  bench:
    desc: "Run benchmarks"
    cmds:
      - task: fmt
      - go test {{.testArgs}} -count=1 -tags integration -bench=. -benchtime=10s -benchmem ./...

  fmt:
    internal: true
    desc: "Invoke fmt"
    cmds:
      - goimports -w .
      - go fmt ./...

  cover:
    desc: "Show source coverage"
    aliases: [coverage, cov]
    cmds:
      - go tool cover -func=rate.cov

  uncover:
    desc: "Show uncovered source"
    cmds:
      - uncover rate.cov

  lint:
    desc: "Lint docs"
    cmds:
      - schema-gen extract -o - | schema-gen lint -i -

  install:uncover:
    desc: "Install uncover"
    internal: true
    env:
      GOBIN: /usr/local/bin
    cmds:
      - go install github.com/gregoryv/uncover/...@latest
