---
version: "3"

tasks:
  gen:
    desc: "Generate package documentation"
    cmds:
      - schema-gen extract -o - | schema-gen markdown -i - --skip "OldOAS" --trim "Tyk classic API definition" -o schema/x-tyk-gateway.md --root XTykAPIGateway
