---
version: "3"

vars:
  testArgs: -v

tasks:
  default:
    desc: "Run tests"
    cmds:
      - task: fmt
      - go test {{.testArgs}} -count=1 -cover -coverprofile=rate.cov .
      - task: cover

  fmt:
    internal: true
    desc: "Invoke fmt"
    cmds:
      - goimports -w .
      - go fmt ./...

  cover:
    desc: "Show source coverage"
    aliases: [coverage, cov]
    cmds:
      - go tool cover -func=rate.cov

  uncover:
    desc: "Show uncovered source"
    cmds:
      - uncover rate.cov

  install:uncover:
    desc: "Install uncover"
    internal: true
    env:
      GOBIN: /usr/local/bin
    cmds:
      - go install github.com/gregoryv/uncover/...@latest
