# Generated by: tyk-ci/wf-gen
# Generated on: Tue 27 Apr 12:03:55 UTC 2021

# Generation commands:
# ./pr.zsh -title releng: [TD-309] multiarch manifests for CI -branch releng/ecr
# m4 -E -DxREPO=tyk


data "terraform_remote_state" "integration" {
  backend = "remote"

  config = {
    organization = "Tyk"
    workspaces = {
      name = "base-prod"
    }
  }
}

output "tyk" {
  value = data.terraform_remote_state.integration.outputs.tyk
  description = "ECR creds for tyk repo"
}

output "region" {
  value = data.terraform_remote_state.integration.outputs.region
  description = "Region in which the env is running"
}
