---
version: "3"

vars:
  tag: v5.2.1-dev
  base: tykio/golang-cross:1.19-bullseye
  sha:
    sh: git rev-parse HEAD
  root:
    sh: git rev-parse --show-toplevel

tasks:
  build:
    desc: "Build plugin compiler"
    dir: '{{.root}}'
    cmds:
      - docker build --build-arg GO_VERSION=1.19 --build-arg BASE_IMAGE={{.base}} --build-arg GITHUB_TAG={{.tag}} --build-arg GITHUB_SHA={{.sha}} --platform=linux/amd64 --rm -t internal/plugin-compiler -f ci/images/plugin-compiler/Dockerfile .
