---
version: "3"

tasks:
  default:
    desc: "Configure tracetest"
    deps:
      - install
    cmds:
      - tracetest configure -g --endpoint http://localhost:11633

  install:
    internal: true
    desc: "Install tracetest"
    status:
      - type tracetest
    cmds:
      - cmd: brew install kubeshop/tracetest/tracetest@0.12.2
        platforms: [darwin]
      - cmd: sudo apt-get install kubeshop/tracetest/tracetest=0.12.2
        platforms: [linux]

