#!/bin/bash

# Generated by: tyk-ci/wf-gen
# Generated on: Tue Jan  4 15:29:13 UTC 2022

# Generation commands:
# ./pr.zsh -p -base aws/TD-664-r4-0 -branch aws/TD-664-r4-0 -title sync m4 templates -repos tyk
# m4 -E -DxREPO=tyk


echo "Creating user and group..."
GROUPNAME="tyk"
USERNAME="tyk"

getent group "$GROUPNAME" >/dev/null || groupadd -r "$GROUPNAME"
getent passwd "$USERNAME" >/dev/null || useradd -r -g "$GROUPNAME" -M -s /sbin/nologin -c "Tyk service user" "$USERNAME"


# This stopped being a symlink in PR #3569
if [ -L /opt/tyk-gateway/coprocess/python/proto ]; then
    echo "Removing legacy python protobuf symlink"
    rm /opt/tyk-gateway/coprocess/python/proto
fi
