#!/bin/sh

# Generated by: tyk-ci/wf-gen
# Generated on: Thu Jan 20 18:46:03 UTC 2022

# Generation commands:
# ./pr.zsh -base master -branch master-m4-sync -title Sync master with m4 release engineering templates -repos tyk,tyk-pump,tyk-analytics,tyk-identity-broker
# m4 -E -DxREPO=tyk


if command -V systemctl >/dev/null 2>&1; then
    if [ ! -f /lib/systemd/system/tyk-gateway.service ]; then
        cp /opt/tyk-gateway/install/inits/systemd/system/tyk-gateway.service /lib/systemd/system/tyk-gateway.service
    fi
else
    if [ ! -f /etc/init.d/tyk-gateway ]; then
        cp /opt/tyk-gateway/install/inits/sysv/init.d/tyk-gateway /etc/init.d/tyk-gateway
    fi
fi
