# Running this taskfile ensures that markdowns are
# consistently formatted according to mdox rules.
---
version: "3"

vars:
  root:
    sh: git rev-parse --show-toplevel

tasks:
  generate:
    desc: "Generate documentation"
    aliases: [codegen, gen]
    cmds:
      - task: generate:docs
      - task: fmt

  generate:docs:
    internal: true
    desc: "Generate plugin API godocs."
    cmds:
      - cd '{{.root}}/internal' && go-fsck docs ./... > ../docs/dev/internal.md
      - cd '{{.root}}/apidef/oas' && go-fsck docs . > ../../docs/dev/oas-apis.md
      - cd '{{.root}}/ctx'      && go-fsck docs . >  ../docs/dev/plugin-apis.md
      - cd '{{.root}}/user'     && go-fsck docs . >> ../docs/dev/plugin-apis.md
      - cd '{{.root}}/storage'  && go-fsck docs . >> ../docs/dev/plugin-apis.md
      - cd '{{.root}}/log'      && go-fsck docs . >> ../docs/dev/plugin-apis.md

  fmt:
    desc: "Run mdox to format markdowns"
    cmds:
      - cd '{{.root}}/docs' && mdox fmt --no-soft-wraps $(find -name '*.md') && cd ..

  deps:
    desc: "Install dependencies"
    status:
      - type mdox
    cmds:
      - go install github.com/bwplotka/mdox@latest
