---
services:
  httpbin:
    image: tykio/ci-tools:latest
    networks:
      - proxy
    volumes:
      - ./logs:/logs:rw
    entrypoint:
      - /usr/local/bin/httpbin-logserver
    command:
      - '-addr'
      - ':80'
      - '-output'
      - '/logs/service.json'
