name: Dependency Impact Review

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

# Define permissions needed for the workflow
permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  dependency_review:
    if: |
      (github.event_name == 'pull_request' && (github.event.action == 'opened' || github.event.action == 'synchronize')) ||
      (github.event_name == 'issue_comment' && github.event.action == 'created' && 
       (contains(github.event.comment.body, '/dependency') || contains(github.event.comment.body, '/deps')))
    uses: buger/probe/.github/workflows/probe.yml@main
    with:
      command_prefix: "/dependency"
      prompt: ".probe/dependency-impact-reviewer.md"
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.PROBE_ANTHROPIC_API_KEY }}
      ANTHROPIC_API_URL: ${{ secrets.PROBE_ANTHROPIC_URL }}