name: Dependency Impact Review

on:
  pull_request:
    types: [opened, synchronize]
  issue_comment:
    types: [created]

# Define permissions needed for the workflow
permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  dependency_review:
    uses: probelabs/probe/.github/workflows/probe.yml@main
    with:
      command_prefix: "/dependency"
      prompt: ".probe/dependency-impact-reviewer.md"
      update_existing_comment: true
      update_comment_marker: "Tyk Gateway Dependency Impact Reviewer"
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.PROBE_ANTHROPIC_API_KEY }}
      ANTHROPIC_API_URL: ${{ secrets.PROBE_ANTHROPIC_URL }}