name: Validate PR against Jira

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

concurrency:
  group: jira-validator-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  validate:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Validate Jira ticket
        uses: TykTechnologies/jira-linter@38a9cabef56171c4e52ea698fa7be3db5fca3a49  # main
        with:
          jira-base-url: 'https://tyktech.atlassian.net'
          jira-user-email: ${{ secrets.JIRA_USER_EMAIL }}
          jira-api-token: ${{ secrets.JIRA_TOKEN }}
