name: Validate PR against Jira

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

concurrency:
  group: jira-validator-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  validate:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Validate Jira ticket
        uses: TykTechnologies/github-actions/jira-linter@production
        with:
          jira-base-url: ${{ secrets.JIRA_BASE_URL }}
          jira-read-auth: ${{ secrets.JIRA_READ_AUTH }}
