name: Validate PR against Jira

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

concurrency:
  group: jira-validator-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  validate:
    if: ${{ !github.event.pull_request.draft }}
    runs-on: ubuntu-latest
    steps:
      - name: Validate Jira ticket
        uses: TykTechnologies/jira-linter@d4f84b2ca8520dbb52971fbdc8c82a91dbaf18d5
        with:
          jira-base-url: 'https://tyktech.atlassian.net'
          jira-api-token: ${{ secrets.JIRA_TOKEN }}
