# yamllint disable rule:truthy
---
name: CI lint

# API Changes (godoc) and JIRA validation only apply to PRs.
# Branches are not important, supports chaining PRs.

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  dep-guard:
    uses: TykTechnologies/github-actions/.github/workflows/dependency-guard.yml@6c675f850b1ba48da2bcd1b6caa16f9cf154e9e3  # main
    permissions:
      contents: read

  godoc:
    needs: [dep-guard]
    if: ${{ !github.event.pull_request.draft }}
    uses: TykTechnologies/github-actions/.github/workflows/godoc.yml@92b66e740444aba67fdbc96c07c69e1c6dd6f32d  # main
    secrets:
      ORG_GH_TOKEN: ${{ secrets.ORG_GH_TOKEN }}
    with:
      go-version: stable
