# yamllint disable rule:truthy
---
name: CI lint

# API Changes (godoc) and JIRA validation only apply to PRs.
# Branches are not important, supports chaining PRs.

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  dep-guard:
    uses: TykTechnologies/github-actions/.github/workflows/dependency-guard.yml@d3fa20888fa2878e877e22bb7702141217290e7c  # main
    permissions:
      contents: read

  godoc:
    needs: [dep-guard]
    if: ${{ !github.event.pull_request.draft }}
    uses: TykTechnologies/github-actions/.github/workflows/godoc.yml@d3fa20888fa2878e877e22bb7702141217290e7c  # main
    secrets:
      ORG_GH_TOKEN: ${{ secrets.ORG_GH_TOKEN }}
    with:
      go-version: stable
