name: Opentelemetry e2e

on:
  pull_request:
    branches: [master]

jobs:
  e2e:
    name: Opentelemetry e2e
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          version: 3
      - name: Setup Golang
        uses: actions/setup-go@v4
        with:
          go-version: 1.19  
      - name: Setup e2e testing enviroment
        run: task test:opentelemetry:setup
      - name: Run e2e opentelemetry tests
        run: task test:opentelemetry:test
      - name: Stop e2e
        if: always()
        run: task test:opentelemetry:teardown