name: Probe Reviewers (Connectivity & Dependency Impact)

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, synchronize]
    branches: [master]

# Define permissions needed for the workflow
permissions:
  issues: write
  pull-requests: write
  contents: write

jobs:
  # Manual trigger via comments
  connectivity_reviewer:
    if: github.event_name == 'issue_comment'
    uses: buger/probe/.github/workflows/probe.yml@main
    with:
      command_prefix: "/connectivity-reviewer"
      allow_edit: true
      prompt: ./.probe/connectivity-reviewer.md
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.PROBE_ANTHROPIC_API_KEY }}
      ANTHROPIC_API_URL: ${{ secrets.PROBE_ANTHROPIC_URL }}
      APP_ID: ${{ secrets.PROBE_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.PROBE_APP_PRIVATE_KEY }}

  dependency_impact_reviewer:
    if: github.event_name == 'issue_comment'
    uses: buger/probe/.github/workflows/probe.yml@main
    with:
      command_prefix: "/dependency-impact-reviewer"
      allow_edit: true
      prompt: ./.probe/dependency-impact-reviewer.md
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.PROBE_ANTHROPIC_API_KEY }}
      ANTHROPIC_API_URL: ${{ secrets.PROBE_ANTHROPIC_URL }}
      APP_ID: ${{ secrets.PROBE_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.PROBE_APP_PRIVATE_KEY }}

  # Automatic trigger on PR
  auto_connectivity_reviewer:
    if: github.event_name == 'pull_request'
    uses: buger/probe/.github/workflows/probe.yml@main
    with:
      command_prefix: "auto-connectivity-review"
      allow_edit: true
      prompt: ./.probe/connectivity-reviewer.md
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.PROBE_ANTHROPIC_API_KEY }}
      ANTHROPIC_API_URL: ${{ secrets.PROBE_ANTHROPIC_URL }}
      APP_ID: ${{ secrets.PROBE_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.PROBE_APP_PRIVATE_KEY }}

  auto_dependency_impact_reviewer:
    if: github.event_name == 'pull_request'
    uses: buger/probe/.github/workflows/probe.yml@main
    with:
      command_prefix: "auto-dependency-impact-review"
      allow_edit: true
      prompt: ./.probe/dependency-impact-reviewer.md
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.PROBE_ANTHROPIC_API_KEY }}
      ANTHROPIC_API_URL: ${{ secrets.PROBE_ANTHROPIC_URL }}
      APP_ID: ${{ secrets.PROBE_APP_ID }}
      APP_PRIVATE_KEY: ${{ secrets.PROBE_APP_PRIVATE_KEY }}