name: Ask questions about the code

on:
  issue_comment:
    types: [created]

# Define permissions needed for the workflow
permissions:
  issues: write
  pull-requests: write
  contents: read

jobs:
  dependency_review:
    uses: probelabs/probe/.github/workflows/probe.yml@main
    with:
      command_prefix: "/probe"
    secrets:
      ANTHROPIC_API_KEY: ${{ secrets.PROBE_ANTHROPIC_API_KEY }}
      ANTHROPIC_API_URL: ${{ secrets.PROBE_ANTHROPIC_URL }}
