---
name: "Lint swagger schema"

on:
  pull_request:
    paths:
      - 'swagger.yml'
jobs:
  redocly_validator:
    runs-on: ubuntu-latest
    name: Validate the swagger with redocly cli

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Validate OpenAPI definition with redocly
        run: |
          npm install @redocly/cli -g
          redocly lint swagger.yml --config=redocly.yml


