# Keep the docs on tyk-docs in sync with this branch's docs

name: Update OAS docs

on:
  push:
    branches:
      - temporarily-suspended
    paths:
      - apidef/oas/schema/x-tyk-gateway.md

jobs:
  sync:
    name: tyk-oas-docs
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@d72941d797fd3113feb6b93fd0dec494b13a2547 # v1
        with:
          app-id: ${{ secrets.PROBE_APP_ID }}
          private-key: ${{ secrets.PROBE_APP_PRIVATE_KEY }}
          owner: TykTechnologies

      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ steps.app-token.outputs.token }}
          repository: TykTechnologies/tyk-docs
          event-type: tyk-oas-docs
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
